spring.application.name=Project_HeThongSanGiaoDichLamViecVaTuyenDung
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/db_cntt3_api_ss4?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=ChuoiBaoMatCuaHeThongSanGiaoDichViecLamVaTuyenDungPTIT2026!@#
# Th?i gian s?ng c?a Access Token: 15 phút (900000 ms)
app.jwt.access-expiration=900000
# Th?i gian s?ng c?a Refresh Token: 7 ngày (604800000 ms)
app.jwt.refresh-expiration=604800000

spring.servlet.multipart.enabled=true
# Gi?i h?n dung l??ng t?i ?a c?a m?t file (Ví d?: CV max 5MB)
spring.servlet.multipart.max-file-size=5MB
# Gi?i h?n t?ng dung l??ng c?a toàn b? request
spring.servlet.multipart.max-request-size=15MB

spring.mail.host=smtp.gmail.com  
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true