spring.application.name=Project_HeThongSanGiaoDichLamViecVaTuyenDung
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/db_cntt3_api_ss4?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=ChuoiBaoMatCuaHeThongSanGiaoDichViecLamVaTuyenDungPTIT2026!@#
app.jwt.access-expiration=900000
app.jwt.refresh-expiration=604800000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

spring.mail.host=smtp.gmail.com  
spring.mail.port=587
spring.mail.username=email_cua_ban@gmail.com
spring.mail.password=rlfkzhvmvgixtixj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# C?u hình Redis (FR-13: Token Blacklist)
spring.data.redis.host=localhost
spring.data.redis.port=6379